import { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    slug: 'rave-rebels-2025-the-ship',
    title: 'Rave Rebels 2025 | The Ship',
    description: 'Stage design for Belgium\'s largest indoor rave',
    category: 'music',
    year: 2025,
    date: 'November 8, 2025',
    region: 'europe',
    environment: ['stage-design'],
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&h=800&fit=crop',
    featured: true,
  },
  {
    id: '2',
    slug: 'point-of-singularity',
    title: 'Point of Singularity',
    description: 'The world\'s first immersive AV installation inside a 360° LED sphere',
    category: 'museums-exhibitions',
    year: 2025,
    date: 'April 27, 2025',
    region: 'europe',
    environment: ['installations'],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=800&fit=crop',
    featured: true,
  },
  {
    id: '3',
    slug: 'the-legend-of-the-titanic',
    title: 'The Legend of the Titanic',
    description: 'Immersive multimedia exhibition experience',
    category: 'museums-exhibitions',
    year: 2024,
    date: 'September 15, 2024',
    region: 'europe',
    environment: ['installations', 'special-projects'],
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=800&fit=crop',
    featured: true,
  },
  {
    id: '4',
    slug: 'phish-concert-sphere',
    title: 'Phish Concert | Sphere, Las Vegas',
    description: 'Visual content and stage design for Phish at Sphere',
    category: 'music',
    year: 2024,
    date: 'April 18, 2024',
    region: 'americas',
    environment: ['stage-design', 'show-production'],
    imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&h=800&fit=crop',
    featured: true,
  },
  {
    id: '5',
    slug: 'afc-asian-cup-2023-opening-ceremony',
    title: 'AFC Asian Cup 2023 Opening Ceremony',
    description: 'Spectacular opening ceremony production',
    category: 'shows-events',
    year: 2023,
    date: 'January 12, 2024',
    region: 'middle-east-africa',
    environment: ['show-production', 'public-events'],
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=800&fit=crop',
    featured: true,
  },
  {
    id: '6',
    slug: 'outline-festival-2025',
    title: 'Outline Festival 2025',
    description: 'Stage design for the main stage of an annual music and art festival',
    category: 'music',
    year: 2025,
    date: 'July 10, 2025',
    region: 'europe',
    environment: ['stage-design'],
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&h=800&fit=crop',
  },
  {
    id: '7',
    slug: 'light-is-dead-nur-2025',
    title: 'Light Is Dead | NUR 2025',
    description: 'Installation for the NUR media art festival in an underground gallery',
    category: 'museums-exhibitions',
    year: 2025,
    date: 'May 23, 2025',
    region: 'europe',
    environment: ['installations'],
    imageUrl: 'https://images.unsplash.com/photo-1551993005-75c4131b6bd8?w=1200&h=800&fit=crop',
  },
  {
    id: '8',
    slug: 'argy-new-world-soho-garden-dubai',
    title: 'ARGY "New World" | Soho Garden Dubai',
    description: 'Stage design and visual content for the show of melodic techno musician – ARGY',
    category: 'music',
    year: 2025,
    date: 'January 1, 2025',
    region: 'middle-east-africa',
    environment: ['stage-design', 'show-production'],
    imageUrl: 'https://images.unsplash.com/photo-1571266028243-d220c6e2e2e4?w=1200&h=800&fit=crop',
  },
  {
    id: '9',
    slug: 'tutankhamun-in-search-of-eternal-life',
    title: 'Tutankhamun: In Search of Eternal Life',
    description: 'Immersive exhibition exploring ancient Egyptian culture',
    category: 'museums-exhibitions',
    year: 2024,
    date: 'March 20, 2024',
    region: 'middle-east-africa',
    environment: ['installations', 'special-projects'],
    imageUrl: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1200&h=800&fit=crop',
  },
  {
    id: '10',
    slug: 'galaxy-unpacked-2024',
    title: 'Galaxy Unpacked 2024',
    description: 'Samsung product launch event production',
    category: 'shows-events',
    year: 2024,
    date: 'January 17, 2024',
    region: 'asia',
    environment: ['show-production', 'public-events'],
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&h=800&fit=crop',
  },
  {
    id: '11',
    slug: 'billie-eilish-tour',
    title: 'Billie Eilish',
    description: 'Visual content and stage design for world tour',
    category: 'music',
    year: 2024,
    date: 'February 29, 2024',
    region: 'americas',
    environment: ['stage-design', 'show-production'],
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=800&fit=crop',
  },
  {
    id: '12',
    slug: 'lamborghini-revuelto',
    title: 'Lamborghini Revuelto',
    description: 'Product launch event with immersive visuals',
    category: 'shows-events',
    year: 2023,
    date: 'March 29, 2023',
    region: 'europe',
    environment: ['show-production', 'special-projects'],
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&h=800&fit=crop',
  },
  {
    id: '13',
    slug: 'mater-terrae-videocitta-rome',
    title: 'Mater Terrae | Videocitta Rome',
    description: 'Large-scale projection mapping installation',
    category: 'shows-events',
    year: 2023,
    date: 'July 14, 2023',
    region: 'europe',
    environment: ['media-facades', 'public-events'],
    imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=1200&h=800&fit=crop',
  },
  {
    id: '14',
    slug: 'outline-festival-2024',
    title: 'Outline Festival 2024',
    description: 'Annual music and art festival stage design',
    category: 'music',
    year: 2024,
    date: 'July 12, 2024',
    region: 'europe',
    environment: ['stage-design'],
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1200&h=800&fit=crop',
  },
  {
    id: '15',
    slug: 'hyperfeeling-installation-balloon-museum',
    title: 'The Hyperfeeling installation | Balloon Museum',
    description: 'Interactive multimedia installation',
    category: 'museums-exhibitions',
    year: 2024,
    date: 'May 10, 2024',
    region: 'americas',
    environment: ['installations'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop',
  },
];

export const categories = [
  { id: 'music', label: 'Music' },
  { id: 'museums-exhibitions', label: 'Museums & exhibitions' },
  { id: 'shows-events', label: 'Shows & events' },
] as const;

export const regions = [
  { id: 'europe', label: 'Europe' },
  { id: 'asia', label: 'Asia' },
  { id: 'middle-east-africa', label: 'Middle East and Africa' },
  { id: 'americas', label: 'Americas' },
] as const;

export const environments = [
  { id: 'show-production', label: 'Show Production' },
  { id: 'stage-design', label: 'Stage Design' },
  { id: 'media-facades', label: 'Media Facades' },
  { id: 'special-projects', label: 'Special Projects' },
  { id: 'public-events', label: 'Public Events' },
  { id: 'installations', label: 'Installations' },
] as const;
